### ISSUE TITLE
Parse external debug symbols

### ISSUE THREAD

**Issue by apangin** [apangin/async-profiler#18]

**Comment by goldshtn** [comment]
I have just recently done something similar for [BCC](https://github.com/iovisor/bcc) in [this PR](https://github.com/iovisor/bcc/pull/967). Specifically [this commit](https://github.com/iovisor/bcc/pull/967/commits/01553853352b5e86704c7fd37f2cfadbf3ef2d6d). I don't mind implementing this here as well, if you'd like.

**Comment by goldshtn** [comment]
Done in #23.
