### ISSUE TITLE
Allow redirecting all output to a file

### ISSUE THREAD

**Issue by goldshtn** [apangin/async-profiler#19]
Currently, only the raw stack dumps can be redirected to a file. The rest of the output goes to the Java program's stdout, which can be undesired in case that output is parsed or redirected in the first place.

I propose another agent parameter: `file:<path-to-file>`, which can be appended to the start command. For example: `jattach ... file:/tmp/profile.log,interval:1000000,start`.

**Comment by goldshtn** [comment]
@apangin Does the `file:<path-to-file>` parameter make sense?

**Comment by apangin** [comment]
Yes, it is fine. I suppose this parameter will also replace an optional file name in `dumpRawTraces` command.
