### ISSUE TITLE
CI build

### ISSUE THREAD

**Issue by goldshtn** [apangin/async-profiler#20]
Would we want to integrate with some CI build solution so that we can 1) verify pull requests automatically before merging, and 2) produce binary packages for Debian/RH?

**Comment by apangin** [comment]
Yes, probably. Do you already have anything specific in mind?

**Comment by goldshtn** [comment]
Travis is easy enough to use, and free in perpetuity for open source projects. Integrates really well with GitHub. I'll give it a shot, it might require permissions only you as the repo owner have - but I will try to set it up myself first.
