### ISSUE TITLE
Add "info" command

### ISSUE THREAD

**Issue by alekseytomin** [apangin/async-profiler#27]
Please to add "jattach.sh -p XXXX -i" - print info (profile was (not)attached and any other information).

**Comment by goldshtn** [comment]
Sorry, not sure what you mean by that. What would the -i flag do? What is jattach.sh?

**Comment by alekseytomin** [comment]
Sorry, profiler.sh :)

I want to see status:
"profiler was not attached to this process"
"profiler attached at 123434 seconds"

**Comment by goldshtn** [comment]
So would you want the -i switch to print this information _after_ you already attached the profiler? Or is that something you want each command to print as you execute it? It would be nice if you could mock the terminal output you would expect, to understand this better.

**Comment by goldshtn** [comment]
@alekseytomin Ping.

**Comment by alekseytomin** [comment]
I will create merge request in this week.

**Comment by apangin** [comment]
Added `status` command.
