### ISSUE TITLE
Revise usage of jmethodID to distinguish between Java methods and native symbols

### ISSUE THREAD

**Issue by apangin** [apangin/async-profiler#32]
`jmethodID` has ambiguous meaning in the profiler: it can denote either Java method or a native symbol. Currently this type is encoded in the highest bit of `jmethodID` pointer. This works well on 64-bit Linux, but may not be appropriate for 32-bit platforms (e.g. linux-arm).

**Comment by sergey-nbl** [comment]
Are you referring to isString, asString and asJavaMethod functions?

**Comment by apangin** [comment]
Yes
