### ISSUE TITLE
It seems that huge amount of sampling is omited from dump (and flame graph)

### ISSUE THREAD

**Issue by Fuud** [apangin/async-profiler#35]
Hello,

I am profiling Cassandra.
At the end of profiling I get:
```
--- Execution profile ---
Total:                 230393
Non-Java:              26372 (11.45%)
GC active:             62 (0.03%)
Unknown (native):      83399 (36.20%)
Not walkable (native): 6 (0.00%)
Unknown (Java):        1016 (0.44%)
Not walkable (Java):   7 (0.00%)
Deopt:                 322 (0.14%)
```

As I can understand, ~50% of perf events was captured at points where `asyncGetCallTrace` can not reconstruct Stack Traces. Am I right? 
And this events does not included in Flame Graph. May be them should be included as "unknown" method to indicate that signigicant amount of CPU usage can not be recognized.

Thanks.

**Comment by apangin** [comment]
Even if AsyncGetCallTrace fails, the native part of a stack trace should be still visible on a flame graph. Can you share a flame graph or provide a reduced test case to check if the results are sane?

It's probably worth adding a fake frame with AGCT error code at the bottom of such samples.

**Comment by Fuud** [comment]
Here it is:
1) https://drive.google.com/file/d/0B2WZhuW_tSiWQzkxb1NGbW5ubTQ/view?usp=sharing
2) https://drive.google.com/file/d/0B2WZhuW_tSiWc2tqNS0xX3FWM2c/view?usp=sharing

Second was done with `-XX:+DebugNonSafepoints`

You can see the difference by searching MON_R_CompactionExecutor.run (it exists at second FG and does not exist at first one).

**Comment by apangin** [comment]
The graphs look sane. They  also display VM activity: GC, compiler and more.
Note that samples of VMThread, WatherThread and GC threads will be counted as "Non-Java", and the samples of Compiler threads will be counted as "Unknown (native)", since CompilerThread inherits JavaThread in HotSpot for some reason.

Does this answer your question? I understand that AsyncGetCallTrace error codes may look confusing, but I'm not sure what to do with them. Native code unrecognized by AsyncGetCallTrace is still displayed in FlameGraphs though.

**Comment by Fuud** [comment]
Yes both graphs looks sane. And it is the problem. Because both graphs display same application is (near) same state. 
Absent of CompactionExecutor at first graph means data displayed is unreliable. 
May be it is better to display at flame-graph amount of totaly unrecognized samples. It will help to understand if displayed "flames" have real mean.

**Comment by apangin** [comment]
Do you have a clear indication of a problem? I don't see it yet. If there is no `CompactionExecutor` in one profile, it does not yet mean there should be. E.g. compaction is a periodic process in Cassandra that does not happen *always*.

**Comment by apangin** [comment]
One possible reason why some threads may appear missing in a profile is a failure to allocate perf_event descriptor for these threads. Each profiled thread requires one perf_event descriptor and one mmap'ed region of 8kB size.

That is, to profile an application with N threads make sure the following limits are satisfied:

- `ulimit -n` > N
- `/proc/sys/vm/max_map_count` > N
- `/proc/sys/kernel/perf_event_mlock_kb` > 8*N

Anyway, in case of perf_event allocation failure, an error message will be printed to `stderr` of the target Java process.

**Comment by Fuud** [comment]
>>E.g. compaction is a periodic process in Cassandra that does not happen always.
Sorry. I should be more clear. I checked that Compaction was running during profiling and it takes significant CPU.

I search through logs and found this;
```
...
mmap failed: Operation not permitted
mmap failed: Operation not permitted
mmap failed: Operation not permitted
mmap failed: Operation not permitted
...
```
Is it allocation failure?

I have following limits:
```
# ulimit -n
655350

# cat /proc/sys/vm/max_map_count
65530

# cat /proc/sys/kernel/perf_event_mlock_kb
516

```

Our application have about 360 threads. 8*360=2880. Thus I need to setup 3000kb as perf_event_mlock_kb?

**Comment by apangin** [comment]
> Thus I need to setup 3000kb as perf_event_mlock_kb?
Yes, this is most probably the reason. Don't hesitate to set even larger value - this should not be harmful.

If this helps, I'll update the documentation and then mark the issue resolved.

**Comment by apangin** [comment]
Follow up: `perf_event_mlock_kb=516` seems to be the default on most Linux system, which prevents non-root from reliable profiling of applications with more than 64 threads. Too bad, but unfortunately async-profiler cannot do anything about it except proper documentation and error messages. 8kB (2 pages) per thread is already the minimum possible perf_event buffer size.

Just to clarify: threads without allocated perf_event buffer will be completely missing in the profile, i.e. they will not be even counted in `Total` / `Non-Java` / `Unknown` statistics.

**Comment by Fuud** [comment]
I rerun test. It helps. Thank you.

May be we can somehow display such threads in flame graph? It will help to detect such problems quickly.

**Comment by apangin** [comment]
I've fixed the problem by allowing to collect at least Java stack traces when perf_event_mlock_kb overflow happens. Native and kernel stack traces will be missing for these threads though.

Added documentation paragraph.
